### ISSUE TITLE
dyn_dnode_server.c:281 dyn: accept on p 8 failed: Too many open files

### ISSUE THREAD

**Issue by nyaapa** [Netflix/dynomite#140]
I have this error after ~ 12 hours server start.
used commands: evalsha, expire, hmset, incrBy, keys, hmget, get
config: 
```
dyn_o_mite:
  datacenter: default_dc
  dyn_listen: ostack03:8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - ostack01:8101:rack:default_dc:2900888940
  - ostack02:8101:rack:default_dc:1094803232
  listen: ostack03:8102
  rack: rack
  servers:
  - 127.0.0.1:6379:1
  tokens: '1795242825'
  redis: true
```
