### ISSUE TITLE
Setting same rack name in different datacenter get SIGNAL 11

### ISSUE THREAD

**Issue by wuyicang** [Netflix/dynomite#142]
If I set the rack name to `default-rack` for both datacenter, the second dynomite will start fail.

```
[Mon Jul 20 15:53:34 2015] dynomite.c:194 dynomite-0.1.19 built for Linux 3.18.0-20-rpi2 armv7l started on pid 28532
[Mon Jul 20 15:53:34 2015] dynomite.c:199 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one
[Mon Jul 20 15:53:34 2015] dyn_stats.c:1039 m 4 listening on '0.0.0.0:22222'
[Mon Jul 20 15:53:34 2015] dyn_proxy.c:211 p 8 listening on '0.0.0.0:8102' in redis pool 0 'raspberry-pi-chimera' with 1 servers
[Mon Jul 20 15:53:34 2015] dyn_dnode_server.c:195 dyn: p 9 listening on '0.0.0.0:8101' in redis pool 0 'raspberry-pi-chimera' with 1 servers
[Mon Jul 20 15:53:34 2015] dyn_signal.c:127 signal 11 (SIGSEGV) received, core dumping
Segmentation fault (core dumped)
```
- Here is my configuration file in one datacenter(shanghai):

```
raspberry-pi-chimera:
  datacenter: shanghai
  rack: default-rack
  dyn_listen: 0.0.0.0:8101
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '2035160051'
  redis: true
  secure_server_option: datacenter
  pem_key_file: /var/dynomite/dynomite.pem
  dyn_seeds:
  - 152.62.40.200:8101:default-rack:beijing:835488289
```
- Here is my configuration file in other datacenter(beijing):

```
raspberry-pi-chimera:
  datacenter: beijing
  rack: default-rack
  dyn_listen: 0.0.0.0:8101
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '835488289'
  redis: true
  secure_server_option: datacenter
  pem_key_file: /var/dynomite/dynomite.pem  
```

However, if I change the rack name to `default-rack-shanghai` and `default-rack-beijing`, they will work.
