### ISSUE TITLE
Single machine replication

### ISSUE THREAD

**Issue by krisskross** [Netflix/dynomite#143]
Hi

I'm trying dynomite on a single machine with 2 memcachedb instances and a dynomite instance for each of them.

instance1.yml

``` yml
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  listen: 127.0.0.1:8101
  dyn_listen: 127.0.0.1:8102
  dyn_seeds:
   - 127.0.0.1:8101:rack1:dc1:12345678
   - 127.0.0.2:8101:rack1:dc1:101134286

  tokens: '12345678'
  servers:
  - 127.0.0.1:21201:1
```

instance2.yml

``` yml
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  listen: 127.0.0.2:8101
  dyn_listen: 127.0.0.2:8102
  dyn_seeds:
   - 127.0.0.1:8101:rack1:dc1:12345678
   - 127.0.0.2:8101:rack1:dc1:101134286

  tokens: '101134286'
  servers:
  - 127.0.0.1:21202:1
```

I can connect to instance1, but as soon as I connect to instance2 I get a invalid argument. Not sure what the problem is. Is my configuration correct?

Cheers,
-Kristoffer

instance2

``` bash
[Thu Jul 23 15:10:17 2015] dyn_proxy.c:341 accepted c 12 on p 7 from '127.0.0.1:37622'
[Thu Jul 23 15:10:18 2015] dyn_dnode_peer.c:1037 dyn: connect to peer '127.0.0.1:8101:rack1:dc1:12345678'
[Thu Jul 23 15:10:18 2015] dyn_connection.c:524 recv on sd 13 eof rb 0 sb 36
[Thu Jul 23 15:10:18 2015] dyn_core.c:403 req 15 on s 13 timedout
[Thu Jul 23 15:10:18 2015] dyn_core.c:293 dnode close p 13 '127.0.0.1:8101' on event 00FF eof 0 done 0 rb 0 sb 36: Connection timed out
[Thu Jul 23 15:10:18 2015] dyn_dnode_peer.c:527 dyn: dnode_peer_close on peer '127.0.0.1:8101:rack1:dc1:12345678'
[Thu Jul 23 15:10:18 2015] dyn_connection.c:524 recv on sd 12 eof rb 7 sb 41
[Thu Jul 23 15:10:18 2015] dyn_core.c:312 close c 12 '127.0.0.1:37622' on event 00FF eof 1 done 1 rb 7 sb 41  
[Thu Jul 23 15:10:20 2015] dyn_proxy.c:341 accepted c 12 on p 7 from '127.0.0.1:37626'
```

instance1

``` bash
[Thu Jul 23 15:10:18 2015] dyn_proxy.c:341 accepted c 10 on p 7 from '127.0.0.1:49279'
[Thu Jul 23 15:10:18 2015] dyn_core.c:312 close c 10 '127.0.0.1:49279' on event FFFF eof 0 done 0 rb 36 sb 0: Invalid argument
```

**Comment by mfouilleul** [comment]
You shouldn't add the self ip (rack, dc and token) in the dyn_seeds, only the other nodes.

Max.

**Comment by krisskross** [comment]
For some reason github did not register the reply, but I got a mail notification.

> You shouldn't add the self ip (rack, dc and token) in the dyn_seeds, only the other nodes. Max

So I changed the config to this. But I get the same error.
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  listen: 127.0.0.1:8101
  dyn_listen: 127.0.0.1:8102
  dyn_seeds:
   - 127.0.0.2:8101:rack1:dc1:101134286

  tokens: '12345678'
  servers:
  - 127.0.0.1:21201:1
```

**Comment by mfouilleul** [comment]
- The port in the dyn_seeds should be the dyn_listen.
- Note that, by default the Dynomite guys has choosen the port 8101 for internal communication and 8102, you switch the both. 

A correct conf will be:

```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  listen: 127.0.0.1:8102
  dyn_listen: 127.0.0.1:8101
  dyn_seeds:
   - 127.0.0.2:8101:rack1:dc1:101134286

  tokens: '12345678'
  servers:
  - 127.0.0.1:21201:1
```

Then, you can connect your clients on the 8102 port.
