### ISSUE TITLE
Write lost during redis server restart

### ISSUE THREAD

**Issue by teodor-pripoae** [Netflix/dynomite#190]
Hi,

I'm running a 3 node test cluster. After I restart one redis node (simulate an upgrade), writes are not replicated to it.

Setup:
- 3 nodes (10.121.0.2, 10.121.0.3, 10.121.0.4), redis server running on standard port.
- stop redis server on server 2.
- if connecting to dynomite on server 2, writes fail. This is expected.
- if connecting to dynomite on server 1, write "foo", everything ok.
- start redis server back on server 2
- servers 1 and 3 have key "foo", server 2 does not have it. (checked manually on each one).
- running `get foo` on dynomite 1 returns result. running it on dynomite 2 returns nil. 

```
# Server 1
dyn_o_mite:
  datacenter: eu-west1
  rack: b
  dyn_listen: 10.121.0.2:8101
  dyn_seeds:
  - 10.121.0.3:8101:c:eu-west1:1383429731
  - 10.121.0.4:8101:d:eu-west1:1383429731
  listen: 10.121.0.2:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
```

````
# server 2
dyn_o_mite:
  datacenter: eu-west1
  rack: c
  dyn_listen: 10.121.0.3:8101
  dyn_seeds:
  - 10.121.0.2:8101:b:eu-west1:1383429731
  - 10.121.0.4:8101:d:eu-west1:1383429731
  listen: 10.121.0.3:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
```

```
# server 3
dyn_o_mite:
  datacenter: eu-west1
  rack: d
  dyn_listen: 10.121.0.4:8101
  dyn_seeds:
  - 10.121.0.2:8101:b:eu-west1:1383429731
  - 10.121.0.3:8101:c:eu-west1:1383429731
  listen: 10.121.0.4:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
```

Provision script
```bash
# provision
NETWORK=test

gcloud compute networks create $NETWORK --range 10.121.0.0/16

gcloud compute instances create red01 --network $NETWORK \
    --boot-disk-size 20GB --boot-disk-type pd-ssd --image ubuntu-14-04 \
    --zone europe-west1-b --machine-type n1-standard-1

gcloud compute instances create red02 --network $NETWORK \
    --boot-disk-size 20GB --boot-disk-type pd-ssd --image ubuntu-14-04 \
    --zone europe-west1-c --machine-type n1-standard-1

gcloud compute instances create red03 --network $NETWORK \
    --boot-disk-size 20GB --boot-disk-type pd-ssd --image ubuntu-14-04 \
    --zone europe-west1-d --machine-type n1-standard-1

gcloud compute instances create t1 --network $NETWORK \
    --boot-disk-size 20GB --boot-disk-type pd-ssd --image ubuntu-14-04 \
    --zone europe-west1-d --machine-type n1-standard-1
```

Install script for each node.
```bash
#!/bin/bash

sudo apt-get update -qq
sudo apt-get -y upgrade
sudo apt-get install -y redis-server git build-essential autoconf libtool libssl-dev

git clone https://github.com/Netflix/dynomite.git
pushd dynomite
  autoreconf -fvi
  ./configure --enable-debug=log
  make
popd
```
