### ISSUE TITLE
Data Replication VS sharding question!

### ISSUE THREAD

**Issue by diegopacheco** [Netflix/dynomite#334]
@ipapapa 

I have a cluster with:
   datacenter -> there is just 1 DC: default_dc.
   rakcs -> there are 3 racks: rack1, rack2, rack3.
   nodes -> there are 3 nodes. 1 node per rack.

Here is the Yaml configuration.  Which was generated with https://github.com/Netflix/dynomite/blob/dev/scripts/dynomite/generate_yamls.py 

172.28.198.118.yml
```yaml
dyn_o_mite:
  datacenter: default_dc
  dyn_listen: 0.0.0.0:8101
  dyn_port: 8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - 172.28.198.18:8101:rack1:default_dc:3635901351
  - 172.28.198.236:8101:rack2:default_dc:1519062062
  listen: 0.0.0.0:8102
  rack: rack3
  servers:
  - 127.0.0.1:6379:1
  timeout: 150000
  tokens: '4046965104'
```
172.28.198.18.yml
```yaml
dyn_o_mite:
  datacenter: default_dc
  dyn_listen: 0.0.0.0:8101
  dyn_port: 8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - 172.28.198.118:8101:rack3:default_dc:4046965104
  - 172.28.198.236:8101:rack2:default_dc:1519062062
  listen: 0.0.0.0:8102
  rack: rack1
  servers:
  - 127.0.0.1:6379:1
  timeout: 150000
  tokens: '3635901351'
```
172.28.198.236.yml
```yaml
dyn_o_mite:
  datacenter: default_dc
  dyn_listen: 0.0.0.0:8101
  dyn_port: 8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - 172.28.198.18:8101:rack1:default_dc:3635901351
  - 172.28.198.118:8101:rack3:default_dc:4046965104
  listen: 0.0.0.0:8102
  rack: rack2
  servers:
  - 127.0.0.1:6379:1
  timeout: 150000
  tokens: '1519062062'
```

The data is being replicated to all nodes. As you can see here.

![replication_dynomite](https://cloud.githubusercontent.com/assets/121278/18357393/adb9b954-75a5-11e6-8985-98061a886e67.png)

Is this expected? 

Cheers,
Diego Pacheco
