### ISSUE TITLE
Dynomite crashing when listening on private_ip vs 0.0.0.0

### ISSUE THREAD

**Issue by danielhochman** [Netflix/dynomite#343]
process crashing every minute or so 

example yml
```
pool0:
  
  dyn_listen: 10.0.6.175:8101
  listen: 10.0.6.175:8102
  
  servers:
  - 127.0.0.1:22120:1
  
  dyn_seed_provider: florida_provider
  tokens: 3722304963
  datacenter: us-east-1
  rack: us-east-1a
  
  data_store: 0
  pem_key_file: /etc/dynomiteredis/dynomite_private_key_UNUSED.pem
  secure_server_option: none
  server_retry_timeout: 30000
  server_failure_limit: 3
```

response from custom florida server
```
$ curl localhost:8080/REST/v1/admin/get_seeds
10.0.11.146:8101:us-east-1a:us-east-1:1336212038|10.0.6.168:8101:us-east-1a:us-east-1:3340530095|10.0.11.144:8101:us-east-1a:us-east-1:1240768321|10.0.11.143:8101:us-east-1a:us-east-1:1145324604|10.0.11.142:8101:us-east-1a:us-east-1:1049880887|10.0.11.141:8101:us-east-1a:us-east-1:954437170|10.0.12.87:8101:us-east-1a:us-east-1:1813430623|10.0.12.88:8101:us-east-1a:us-east-1:1908874340|10.0.13.255:8101:us-east-1a:us-east-1:2386092925|10.0.13.254:8101:us-east-1a:us-east-1:2290649208|10.0.6.169:8101:us-east-1a:us-east-1:3435973812|10.0.0.115:8101:us-east-1a:us-east-1:95443717|10.0.12.84:8101:us-east-1a:us-east-1:1527099472|10.0.0.116:8101:us-east-1a:us-east-1:190887434|10.0.7.42:8101:us-east-1a:us-east-1:3817748680|10.0.12.85:8101:us-east-1a:us-east-1:1622543189|10.0.9.34:8101:us-east-1a:us-east-1:4199523548|10.0.12.86:8101:us-east-1a:us-east-1:1717986906|10.0.15.164:8101:us-east-1a:us-east-1:2863311510|10.0.15.167:8101:us-east-1a:us-east-1:3054198944|10.0.15.166:8101:us-east-1a:us-east-1:2958755227|10.0.10.98:8101:us-east-1a:us-east-1:858993453|10.0.6.170:8101:us-east-1a:us-east-1:3531417529|10.0.12.131:8101:us-east-1a:us-east-1:1431655755|10.0.10.94:8101:us-east-1a:us-east-1:572662302|10.0.10.97:8101:us-east-1a:us-east-1:763549736|10.0.10.96:8101:us-east-1a:us-east-1:668106019|10.0.15.169:8101:us-east-1a:us-east-1:3245086378|10.0.15.168:8101:us-east-1a:us-east-1:3149642661|10.0.10.93:8101:us-east-1a:us-east-1:477218585|10.0.13.248:8101:us-east-1a:us-east-1:2195205491|10.0.13.246:8101:us-east-1a:us-east-1:2004318057|10.0.13.247:8101:us-east-1a:us-east-1:2099761774|10.0.6.175:8101:us-east-1a:us-east-1:3722304963|10.0.6.174:8101:us-east-1a:us-east-1:3626861246|10.0.0.112:8101:us-east-1a:us-east-1:0|10.0.0.121:8101:us-east-1a:us-east-1:286331151|10.0.0.124:8101:us-east-1a:us-east-1:381774868|10.0.14.82:8101:us-east-1a:us-east-1:2672424076|10.0.14.80:8101:us-east-1a:us-east-1:2576980359|10.0.14.85:8101:us-east-1a:us-east-1:2767867793|10.0.9.27:8101:us-east-1a:us-east-1:4104079831|10.0.9.26:8101:us-east-1a:us-east-1:4008636114|10.0.9.23:8101:us-east-1a:us-east-1:3913192397|10.0.14.78:8101:us-east-1a:us-east-1:2481536642|10.0.17.36:8101:us-east-1d:us-east-1:668106019|10.0.17.37:8101:us-east-1d:us-east-1:763549736|10.0.17.34:8101:us-east-1d:us-east-1:477218585|10.0.17.35:8101:us-east-1d:us-east-1:572662302|10.0.16.62:8101:us-east-1d:us-east-1:190887434|10.0.26.105:8101:us-east-1d:us-east-1:2958755227|10.0.26.104:8101:us-east-1d:us-east-1:2863311510|10.0.17.38:8101:us-east-1d:us-east-1:858993453|10.0.22.135:8101:us-east-1d:us-east-1:1717986906|10.0.22.136:8101:us-east-1d:us-east-1:1813430623|10.0.29.119:8101:us-east-1d:us-east-1:3435973812|10.0.29.118:8101:us-east-1d:us-east-1:3340530095|10.0.29.123:8101:us-east-1d:us-east-1:3626861246|10.0.23.76:8101:us-east-1d:us-east-1:2481536642|10.0.23.62:8101:us-east-1d:us-east-1:2290649208|10.0.16.59:8101:us-east-1d:us-east-1:0|10.0.23.61:8101:us-east-1d:us-east-1:2195205491|10.0.20.150:8101:us-east-1d:us-east-1:1049880887|10.0.20.151:8101:us-east-1d:us-east-1:1145324604|10.0.20.152:8101:us-east-1d:us-east-1:1240768321|10.0.20.155:8101:us-east-1d:us-east-1:1336212038|10.0.29.17:8101:us-east-1d:us-east-1:3817748680|10.0.29.124:8101:us-east-1d:us-east-1:3722304963|10.0.26.112:8101:us-east-1d:us-east-1:3054198944|10.0.26.113:8101:us-east-1d:us-east-1:3149642661|10.0.26.97:8101:us-east-1d:us-east-1:3245086378|10.0.23.57:8101:us-east-1d:us-east-1:1908874340|10.0.23.79:8101:us-east-1d:us-east-1:2767867793|10.0.23.78:8101:us-east-1d:us-east-1:2672424076|10.0.16.69:8101:us-east-1d:us-east-1:381774868|10.0.23.75:8101:us-east-1d:us-east-1:2386092925|10.0.29.121:8101:us-east-1d:us-east-1:3531417529|10.0.22.132:8101:us-east-1d:us-east-1:1431655755|10.0.22.133:8101:us-east-1d:us-east-1:1527099472|10.0.22.134:8101:us-east-1d:us-east-1:1622543189|10.0.16.63:8101:us-east-1d:us-east-1:286331151|10.0.23.59:8101:us-east-1d:us-east-1:2004318057|10.0.16.61:8101:us-east-1d:us-east-1:95443717|10.0.23.60:8101:us-east-1d:us-east-1:2099761774|10.0.29.24:8101:us-east-1d:us-east-1:4199523548|10.0.20.148:8101:us-east-1d:us-east-1:954437170|10.0.29.20:8101:us-east-1d:us-east-1:3913192397|10.0.23.77:8101:us-east-1d:us-east-1:2576980359|10.0.29.22:8101:us-east-1d:us-east-1:4008636114|10.0.29.23:8101:us-east-1d:us-east-1:4104079831
```

invocation
```
dynomite -c /etc/dynomiteredis/dynomite_conf.yml -v5 --mbuf-size=4096
```

**Comment by mikramulhaq** [comment]
Here is the investigation so far:

1. I had to update messages value to 20000 otherwise it was crashing for any single message
2. New build requires dyn_seeds, which I added.
3. I increased log level to 7, but don't see anything obvious. Log is here http://pastebin.com/5wMUf2yE
4. There is an interesting pattren for crash frequency. It happens in every {43/44 seconds, 16/17 seconds, 43/44 seconds, 16/17 seconds, ........}. Below are process start times from log.
04:37:34.69261
04:38:18.04311
04:38:34.59801
04:39:17.94811
04:39:34.50383
04:40:18.85396
04:40:35.40820
04:41:18.75852
04:41:35.31573

In this case I was using simple provider. Below is the conf file:
```
pool0:

  dyn_listen: 10.0.11.33:8101
  listen: 10.0.11.33:8102

  servers:
  - 127.0.0.1:22120:1

  dyn_seed_provider: simple_provider
  tokens: 0

  data_store: 0
  pem_key_file: /etc/dynomiteredis/dynomite_private_key_UNUSED.pem
  secure_server_option: none
  server_retry_timeout: 30000
  server_failure_limit: 3
  dyn_seeds:
  - <private ip>:8101:us-east-1a:us-east-1:0
```
