### ISSUE TITLE
Error starting dynomite cluster when a dyn_seeds node is unavailable

### ISSUE THREAD

**Issue by rohitpotnis** [Netflix/dynomite#435]
Follow-up to my earlier issue (#434).

**Question:**
Are the servers mentioned in the * dyn_seeds * section required to be reachable at the start?

**Setup:**

1. 2-node cluster (node1 and node2)
2. **node1 conf:**
```
dyn_o_mite:
  .....
  dyn_seeds:
  - node2:8101:rack1:dc1:1383429731
  dyn_seed_provider: simple_provider
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:22122:1
  .....
```
3. **node2 conf**
```
dyn_o_mite:
  .....
  dyn_seeds:
  - node1:8101:rack1:dc1:1383429731
  dyn_seed_provider: simple_provider
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:22122:1
  .....
```

**Problem:** When I try to start either node1 or node2, I get the following error and the startup fails:
```
....
[2017-04-14 18:52:34.876] dn_resolve_inet:520 address resolution of node 'node2' service '8101' failed: Temporary failure in name resolution
[2017-04-14 18:52:34.876] _dn_free:305 free(0x1231ec0) @ dyn_string.c:59
[2017-04-14 18:52:34.876] conf_handler:1472 conf: directive "dyn_seeds" has an invalid value
....
```
How do we start a cluster where each node in the cluster requires a reference to other nodes in the dyn_seeds but the other nodes are not yet started?

As always, thanks for your help!

Rohit

**Comment by rohitpotnis** [comment]
Update: I had to remove the _dyn_seeds_ entry in _node1_ and kept the _dyn_seeds_ entry in _node2_ pointing to _node1_ in order to start both nodes. Is this correct?

**node1 config**
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: node1:8101
  dyn_seed_provider: simple_provider
  listen: node1:8102
  servers:
  - node1:22122:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: node1:22222
```
**node2 config**
```
dyn_o_mite:
  datacenter: dc2
  rack: rack2
  dyn_listen: node2:8101
  dyn_seeds:
  - node1:8101:rack1:dc1:1383429731
  dyn_seed_provider: simple_provider
  listen: node2:8102
  servers:
  - node2:22122:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: node2:22222
```

Even then, the changes made in one node were not visible in the other. Found that problem was most likely due to sharding  vs replication (since both nodes were on the same rack / dc).
 
When I changed the rack / dc of _node2_ to be different from _node1_, then changes made in _node2_ were visible in _node1_. However, changes made in _node1_ were not visible in _node2_ (possibly because _node1_ not gossipping with _node2 since I had to remove the dyn_seeds information was missing in _node1_ config). Am I missing something?
