### ISSUE TITLE
after some time of inactivity dynomite fials to process 1 request. The next one is ok

### ISSUE THREAD

**Issue by yaklimenko** [Netflix/dynomite#464]
after some time of inactivity dynomite fials to process 1 request. The next one is ok.
dynomite 1 config
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_seeds:
  - 172.30.3.151:8103:rack2:dc1:10000000  
  - 172.30.3.136:8105:rack1:dc2:10000000  
  - 172.30.3.136:8107:rack2:dc2:10000000
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  servers:  
  - redis1:22122:1001
  dyn_seed_provider: dns_provider
  tokens: 10000000
  data_store: 0    
  pem_key_file: /run/secrets/dynomite.pem
  secure_server_option: none        
  read_consistency: DC_QUORUM
  write_consistency: DC_QUORUM
```

dynomite2 config
```
dyn_o_mite:
  datacenter: dc1
  rack: rack2
  dyn_seeds:  
  - 172.30.3.151:8101:rack1:dc1:10000000  
  - 172.30.3.136:8105:rack1:dc2:10000000
  - 172.30.3.136:8107:rack2:dc2:10000000  
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  servers:
  - redis2:22122:1000
  dyn_seed_provider: dns_provider  
  tokens: 10000000
  data_store: 0    
  pem_key_file: /run/secrets/dynomite.pem
  secure_server_option: none        
  read_consistency: DC_QUORUM
  write_consistency: DC_QUORUM
```

Plaese look at logs:
dynomite1
https://gist.github.com/yaklimenko/f5c8e5241289952fa96e312d43c64b4c

dynomite2
https://gist.github.com/yaklimenko/fe8f16aac4a3e5312780ce4e88d0500c

first request was made at 11:41:27, and there was an error
second request was made at 11:41:33 result is OK

What is wrong? Seems like dynomite go to standby mode or something like that if not used. 
Can it be that problem is not enough RAM or may that is the docker network issue. 

Please help
