### ISSUE TITLE
Replication in dynomite not reliable 

### ISSUE THREAD

**Issue by codophobia** [Netflix/dynomite#487]
I have not read anything regarding reliability in replicating data between nodes. I have tried setting up cross data center replication with redis by using dynomite as the proxy. At each data center, I have a single instance of redis in one rack.  

I try inserting up some random keys at one dc and then check if the keys have replicated successfully to the other dc. I see a huge difference in number of keys at both dc.
At dc1:
```
redis-cli flushall
redis-benchmark -p 8102 -t set -r 100000
redis-cli dbsize 
(integer) 63293
```
At dc2:
```
redis-cli dbsize 
(integer) 21517
```
As you can see, many of the keys have not been replicated to dc2. I assume that the replication is not reliable in dynomite.

Here are my config file for both the datacenters:
dc1.yml
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - dc2_ip:8101:rack2:dc2:0
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: 0
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22221
  mbuf_size: 64000
  max_msgs: 1000000
```
dc2.yml
```
dyn_o_mite:
  datacenter: dc2
  rack: rack2
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - dc1_ip:8101:rack1:dc1:0
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: 0
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22221
  mbuf_size: 64000
  max_msgs: 1000000
```

I have tried this with dev branch as well as v0.5.9 branch. Both of them give same type of results. When I decrease the number of random keys for benchmarking, the difference gets smaller.
