### ISSUE TITLE
Unable to sync data between data centers

### ISSUE THREAD

**Issue by venendroid** [Netflix/dynomite#572]
Hi All,

  I have two datacenters with Redis and Dynomite on each: 

DC1:[Sample IP : 30.30.30.30] Has below configuration:
```
dyn_o_mite:
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  tokens: '101134286'
  dyn_seed_provider: simple_provider
  datacenter: dc1
  rack: rack1
  dyn_seeds:
  - 50.50.50.50:8101:rack1:dc1:101134286
  - 50.50.50.50:8102:rack1:dc1:101134286
  servers:
  - 127.0.0.1:22122:1
  data_store: 0
  mbuf_size: 16384
  max_msgs: 300000
```

  Dc2: [Sample IP: 50.50.50.50] has below configuration: 
``` 
dyn_o_mite:
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  tokens: '101134286'
  dyn_seed_provider: simple_provider
  datacenter: dc1
  rack: rack1
  dyn_seeds:
  - 30.30.30.30:8101:rack1:dc1:101134286
  - 30.30.30.30:8102:rack1:dc1:101134286
  servers:
  - 127.0.0.1:22122:1
  data_store: 0
  mbuf_size: 16384
  max_msgs: 300000
```

  
  Internally Dynomite and Redis are able to communicate properly on each DC. When we set a key on dynomite, we are able to data sync to local Redis (confirmed by using redis monitor). But, I don't see data sync between datacenters. Is there any issue with my configs? Am I missing something? Please help.

  PS:// Ports are open and able to telnet between datacenters.
