### ISSUE TITLE
Dynomite: ERROR - Command failed (ERR Peer: Peer Node is not connected)

### ISSUE THREAD

**Issue by khanu** [Netflix/dynomite#661]
Hi,

I am using a 4 node cluster in 2 DCs, with 2 racks in each DC with 1 server each. Here is my dynomite config from one of the nodes :
```
dyn_o_mite:
  datacenter: bdc
  rack: rack1
  dyn_port: 8101
  dyn_seeds:
  - 10.185.135.137:8101:rack1:cdc:4294967295
  - 10.185.135.138:8101:rack2:cdc:4294967295
  - 10.150.38.49:8101:rack2:bdc:4294967295
  dyn_listen: 0.0.0.0:8101
  data_store: 0
  listen: 0.0.0.0:6379
  servers:
  - 127.0.0.1:22122:1
  tokens: 4294967295
  timeout: 150000
```
Redis runs on port 22122 and Dynomite on port 6379.

I have an F5 load balancer in front of the cluster, that looks at both these ports and does not send traffic to any node that has redis or dynomite service not running on them. 

PHP code talks to the F5 Internal IP on port 6379.

So when I try stopping redis service on one of the nodes, the F5 disables that node from rotation, and the other nodes are able to serve traffic correctly.

The problem occurs when I try stopping dynomite service on one of the nodes. In this case: 
1. The F5 disables that node and stops sending it traffic
2. The other nodes, however are not able to serve requests and are throwing out the following error:

`ERROR - Command "SET conditions_and_treatments_terms_[...] a:36:" failed (ERR Peer: Peer Node is not connected)
CRITICAL - Uncaught PHP Exception Predis\Response\ServerException: "ERR Peer: Peer Node is not connected" at /var/www/html/symfony/vendor/predis/predis/src/Client.php line 361
 `

Could you help me with this.

Thanks
