### ISSUE TITLE
redis lua script hangs infinitely

### ISSUE THREAD

**Issue by iTosun** [Netflix/dynomite#689]
Hi,

First of all want to thank you all for this amazing project, really like dynomite! Right now i'm trying to do more advanced stuff with dynomite & redis and lua scripting. But i'm getting some weird results, a particular script is hanging infinitely till i exit it with ctrl+c. The config ```lua-time-limit``` is still default on 5000, so it should time-out after 5 seconds but it does not.

My cluster consists of 1 DC and 2 racks with each 1 node (simple dev setup).  The config of a node looks like this:
```
dyn_o_mite:
  env: network
  listen: session:8102
  datacenter: dev
  rack: r1
  dyn_listen: session:8101
  dyn_port: 8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
  - config_store:8101:r2:dev:2863311530
  servers:
  - 127.0.0.1:6379:1
  timeout: 150000
  tokens: 1431655765
  #secure_server_option: all
  stats_listen: 0.0.0.0:22222
```
The script that i try to run:
```
local ha = ARGV[2] --[[Some unused var to satisfy dynomite requirements--]]

local results = {{'Base:Config', redis.call("HGETALL", "Config:"..ARGV[1])}}

if redis.call("HEXISTS", "Mods:"..ARGV[1], 'req:headers') == 1 then
    table.insert(results, {'Request:Headers', redis.call("HGETALL", "Request:Headers:"..ARGV[1]) })
end

if redis.call("HEXISTS", "Mods:"..ARGV[1], 'req:body') == 1 then
    table.insert(results, {'Request:Body', redis.call("HGETALL", "Request:Body:"..ARGV[1]) })
end

if redis.call("HEXISTS", "Mods:"..ARGV[1], 'resp:headers') == 1 then
    table.insert(results, {'Response:Headers', redis.call("HGETALL", "Response:Headers:"..ARGV[1]) })
end

if redis.call("HEXISTS", "Mods:"..ARGV[1], 'resp:headers') == 1 then
    table.insert(results, {'Response:Headers', redis.call("HGETALL", "Response:Headers:"..ARGV[1]) })
end

if redis.call("HEXISTS", "Mods:"..ARGV[1], 'resp:body') == 1 then
    table.insert(results, {'Response:Body', redis.call("HGETALL", "Response:Body:"..ARGV[1]) })
end

return results
```
redis version: 5.0.4
dynomite version: 0.5.9

The weird thing is this script runs fine in redis it self..
Am i  doing something wrong or is there something else going on?
