### ISSUE TITLE
Add/remove node

### ISSUE THREAD

**Issue by mfouilleul** [Netflix/dynomite#69]
Hi, 

Do you have a procedure to add/remove nodes to share? 

Thank a lot.

Max.

**Comment by mfouilleul** [comment]
Hi, 

Thanks for all you responses. So to be safe I will wait to enable all "auto stuffs" fonctionnalities. In its simple form (statically described in conf file), is Dynomite production ready? Do you use it for real at Netflix?

Best,

Max.

**Comment by timiblossom** [comment]
@mfouilleul - sounds good.  We are going through a series of load tests to prepare for a big deployment with several clusters currently and will deploy on prod very soon.

**Comment by timiblossom** [comment]
@mfouilleul  btw, if you need to supply a list of peers that can be dynamically changed, you can set seed_provider: florida_provide in dynomite.yml.  

Dynomite will load this dyn_florida.c which will keep polling a local rest service to return a list of peers.
You can read more about the local service in this file:
https://github.com/Netflix/dynomite/blob/master/src/seedsprovider/dyn_florida.c#L11

**Comment by timiblossom** [comment]
@mfouilleul just want to update you that we just rolled out 2 big clusters to Prod.  Testing shows that a 3 region cluster (in AWS us-east-1, us-west-2 and eu-west-1) of about 40 nodes in each region can handle 500K read/write RPS with average latency under 1ms and 99th latency around 2.5ms.  We will post the graphs later for more details.  

Btw, my mind has been stuck in coding so I completely forgot to mention that we do have several small Dynomite clusters in Prod prior to the New Year 2015 but they are for smaller traffics.

**Comment by mfouilleul** [comment]
Sounds really good! Thanks for all you updates.

Max.

**Comment by mfouilleul** [comment]
Hello,

I made a simple test:

I have two nodes:
- 192.168.33.40
- 192.168.33.41

On the 40, I start a simple dynomite with the conf: 
dyn_o_mite:
  # Node Location
  env: network
  datacenter: dc1
  rack: rc1

  # Dynomite
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  dyn_seed_provider: florida_provider
  preconnect: true

  # Node Info
  redis: true
  tokens: 0
  servers:
  - 127.0.0.1:6379:1

  # Time Management
  gos_interval: 10000
  timeout: 3000
  server_retry_timeout: 3000

  # Security
  secure_server_option: datacenter
  server_connections: 1
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem

Now I start the 41 in the rack=rc2 and I specified the 40 in the seed list:
dyn_o_mite:
  # Node Location
  env: network
  datacenter: dc1
  rack: rc2

  # Dynomite
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  dyn_seed_provider: florida_provider
  preconnect: true

  # Seeds
  dyn_seeds:
  - 192.168.33.40:8101:rc1:dc1:0

  # Node Info
  redis: true
  tokens: 0
  servers:
  - 127.0.0.1:6379:1

  # Time Management
  gos_interval: 10000
  timeout: 3000
  server_retry_timeout: 3000

  # Security
  secure_server_option: datacenter
  server_connections: 1
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem

When I write on the 41 (port 8102), the keys are well replicated to the 40 (because it knows the topology thanks to the seeds I guess) but when I write on 40, nothing append. 

Can you tell me I misunderstand something because, in my mind the gossiping + the florida_provider serve to discover this kind of topology. 

Note that I see some ineresting debugs in the log when I start my dynomites:
- dyn_gossip.c:847 What?? No rack in Dict for rack         : 'dc1'
-dyn_florida.c:98 Unable to connect the destination

Max.

**Comment by mfouilleul** [comment]
Hello,

I made a simple test:

I have two nodes:
- 192.168.33.40
- 192.168.33.41

On the 40, I start a simple dynomite with the conf: 
```
dyn_o_mite:
  # Node Location
  env: network
  datacenter: dc1
  rack: rc1

  # Dynomite
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  dyn_seed_provider: florida_provider
  preconnect: true

  # Node Info
  redis: true
  tokens: 0
  servers:
  - 127.0.0.1:6379:1

  # Time Management
  gos_interval: 10000
  timeout: 3000
  server_retry_timeout: 3000

  # Security
  secure_server_option: datacenter
  server_connections: 1
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem`
```

Now I start the 41 in the rack=rc2 and I specified the 40 in the seed list:
```
dyn_o_mite:
  # Node Location
  env: network
  datacenter: dc1
  rack: rc2

  # Dynomite
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  dyn_seed_provider: florida_provider
  preconnect: true
  
  # Seeds
  dyn_seeds:
  - 192.168.33.40:8101:rc1:dc1:0

  # Node Info
  redis: true
  tokens: 0
  servers:
  - 127.0.0.1:6379:1
  
  # Time Management
  gos_interval: 10000
  timeout: 3000
  server_retry_timeout: 3000
  
  # Security
  secure_server_option: datacenter
  server_connections: 1
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem`
```

When I write on the 41 (port 8102), the keys are well replicated to the 40 (because it knows the topology thanks to the seeds I guess) but when I write on 40, nothing append. 

Can you tell me I misunderstand something because, in my mind the gossiping + the florida_provider serve to discover this kind of topology. 

Note that I see some ineresting debugs in the log when I start my dynomites:
```
dyn_gossip.c:847 What?? No rack in Dict for rack         : 'dc1'
```
```
dyn_florida.c:98 Unable to connect the destination
```
Max.
