### ISSUE TITLE
Replication not working for Redis

### ISSUE THREAD

**Issue by aratik711** [Netflix/dynomite#765]
Hi,

I have setup Dynomite for Redis, with 3 nodes per DC and 2 DCs.
The 3 nodes per DC are in a cluster.

But the replication doesn't seem to be happening from dc1 to dc2.
If I set a record in DC1 doesn't seem to be added in DC2.

Below is a sample yml for node1 dc1:

```yaml
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 10.128.0.2:7379
  dyn_seeds:
  - 10.128.0.3:7379:rack1:dc1:1431655765
  - 10.128.0.5:7379:rack1:dc1:2863311530
  - 10.166.0.2:7379:rack2:dc2:0
  - 10.166.0.3:7379:rack2:dc2:1431655765
  - 10.166.0.4:7379:rack2:dc2:2863311530
  listen: 10.128.0.2:8379
  servers:
  - 10.128.0.2:7000:1
  tokens: '0'
  secure_server_option: datacenter
  pem_key_file: dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22221
``` 

The token formula is (nodeIndex is 0-based): 
`token = (4294967295 / numberOfNodesInRack) * nodeIndex`

Dynomite version: v0.6.21-rc2
Redis version: 5.0.3
Can someone help with the issue here? I have checked the existing similar issues here, not able to make it work.
