### ISSUE TITLE
question about config dynomite described in wiki

### ISSUE THREAD

**Issue by artarik** [Netflix/dynomite#820]
Hello i have a Misunderstanding about how to configure dynomite fo replicating between two dc
i have a  redis server which work as master-slave and controlled by sentinells. 
My clients can only configuring with single FLOAT IP:PORT which attach on master-redis via keepalived
I need to add a new dc with same config
So as i understand it i need to use [thist config](https://github.com/Netflix/dynomite/wiki/Getting+Started#c-two-nodes-cluster-in-two-datacenters-each-having-one-rack)
Does it mean that i need run 4 replicas of dynomite (2 in each dc) and for dc1 use [this](https://github.com/Netflix/dynomite/blob/dev/conf/redis_dc1.yml) config and for dc2 [this](https://github.com/Netflix/dynomite/blob/dev/conf/redis_dc2.yml)?

if that which ip-address i need to use for communications betwen dc? Does i need add config of second node in field `dyn_seeds`  which placed in the same rack?

**Comment by artarik** [comment]
also i have a problem with replication between 2 nodes in one dc. like  this [issue ](https://github.com/Netflix/dynomite/issues/583)
my dynomite config
1 node:
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - 10.7.10.75:8101:rack2:dc1:0
  listen: 0.0.0.0:16379
  servers:
    - 127.0.0.1:6379:1
  tokens: 0
  secure_server_option: datacenter
  pem_key_file: /etc/ssl/dynamo.pem
  data_store: 0
  stats_listen: 127.0.0.1:22222
  server_retry_timeout: 10000
  read_consistency: DC_ONE
  write_consistency: DC_ONE
  mbuf_size: 16384
  max_msgs: 200000
```
node-2
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - 10.7.10.75:8101:rack2:dc1:0
  listen: 0.0.0.0:16379
  servers:
    - 127.0.0.1:6379:1
  tokens: 0
  secure_server_option: datacenter
  pem_key_file: /etc/ssl/dynamo.pem
  data_store: 0
  stats_listen: 127.0.0.1:22222
  server_retry_timeout: 10000
  read_consistency: DC_ONE
  write_consistency: DC_ONE
  mbuf_size: 16384
  max_msgs: 200000
```
If i stop redis on node 2 and adding some keys in node1 they are not copied on node 2 after i start redis
