### ISSUE TITLE
Best Practice for Redis failure mgmt

### ISSUE THREAD

**Issue by mfouilleul** [Netflix/dynomite#92]
Hi,

I try to simulate a Redis failure during dynomite service is still up & running.

On the host 192.168.33.40 I have two redis, one on 6379 and one on 6380.

```
dyn_o_mite:
  # Node Location
  env: network
  datacenter: dc1
  rack: rc1

  # Dynomite
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  dyn_seed_provider: florida_provider
  preconnect: true

  dyn_seeds:
  - 192.168.33.41:8101:rc2:dc1:0

  # Node Info
  redis: true
  tokens: 0
  servers:
  - 127.0.0.1:6379:1
  - 127.0.0.1:6380:1

  # Time Management
  gos_interval: 10000
  timeout: 3000
  server_retry_timeout: 3000

  # Security
  secure_server_option: datacenter
  server_connections: 1
  auto_eject_hosts: true
  server_failure_limit: 3
  pem_key_file: /etc/dynomite/dynomite.pem
```

Everything are up:
```
root@redis3:~# redis-cli -h 192.168.33.40 -p 8102
192.168.33.40:8102> ping
PONG
```

I kill the redis-server running on 6379 (kill -9 redis-server process).

When I connect to dynomite the service is not available:
```

root@redis3:~# redis-cli -h 192.168.33.40 -p 8102
192.168.33.40:8102> ping
(error) ERR Storage: Connection refused
```

Is this case is managed? Am I doing something wrong?

Max.
